#
#   docker build --tag=poster_cas_image .
#
#   docker run -it -p 9010:9010 poster_cas_image
#

FROM golang:alpine as build-env

RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev

WORKDIR /poster_postgres

COPY . .

RUN go build -o poster_postgres .

CMD ./poster_postgres
