# kubectl apply -f cas-config-map.yml
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: poster-cas-configmap 
data:
  # Configuration values can be set as key-value properties
  GRPC_SERVER_NAME: localhost
  GRPC_SERVER_PORT: "9010"

  DATABASE_USERNAME: golang
  DATABASE_PASSWORD: dsfsdfasda
  DATABASE_HOST: cas-cassandra.db.svc
  DATABASE_PORT: "9042"
  DATABASE_KEYSPACE: json

  DEBUGLEVEL: "2"