#############################
#
# kubectl create ns app
#
# kubectl -n app apply -f deploymet.yaml 
#
# kubectl delete pods <pod tag>
# kubectl delete services poster-cas
# kubectl delelte deployment poster-cas
# 
# kubectl get services -n app
# kubectl get pods -n app
# kubectl get deployments -n app
#
# kubectl logs --follow <name of the pod>
#
# kubectl port-forward -n app service/poster-cas 9010
#
# kubectl get all -n=app
# kubectl get all --all-namespaces
#
# kubectl port-forward --namespace db svc/cas-cassandra 9042:9042 &
#
#
#
#############################
#
apiVersion: v1
kind: Service
metadata:
  name: poster-cas
spec:
  selector:
    app: poster-cas
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poster-cas
  labels:
    app: poster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poster-cas
  template:
    metadata:
      labels:
        app: poster-cas
    spec:
      containers:
      - name: poster-cas
        image: 127.0.0.1:5000/poster_cas_image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9010

