#############################
#
# 
#
##########################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrubber
  labels:
    app: poster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scrubber
  template:
    metadata:
      labels:
        app: scrubber
    spec:
      containers:
      - name: scrubber
        image: scrubber_image
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: scrubber-configmap 
